<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->id();
            $table->string('cate_name')->nullable();
            $table->string('cate_title')->nullable();
            $table->string('cate_keyword')->nullable();
            $table->string('cate_description')->nullable();
            $table->string('cate_thumbnail')->nullable();
            $table->string('cate_thumbnail_title')->nullable();
            $table->string('cate_thumbnail_alt')->nullable();
            $table->string('cate_url')->nullable();
            $table->string('cate_topic')->nullable();
            $table->string('cate_h1')->nullable();
            $table->string('cate_h2')->nullable();
            $table->string('cate_freetag')->nullable();
            $table->string('cate_attr')->nullable();
            $table->string('cate_redirect')->nullable();
            $table->integer('cate_parent_id')->default(0);
            $table->integer('cate_root_id')->default(0);
            $table->integer('cate_level')->default(0);
            $table->boolean('cate_status_display')->default(true);
            $table->boolean('is_menu')->default(false);
            $table->boolean('is_topside')->default(false);
            $table->boolean('is_leftside')->default(false);
            $table->boolean('is_rightside')->default(false);
            $table->boolean('is_bottomside')->default(false);
            $table->integer('cate_priority')->default(1);
            $table->integer('cate_position')->default(1);
            $table->boolean('on_product')->default(false); //('ถ้าเป็น false จะใช้สำหรับ content category');
            $table->boolean('is_main_page')->default(true);
            $table->boolean('is_product_cate')->default(false); //('ถ้าเป็น true จะใช้สำหรับเมนู product category')
            $table->dateTime('cate_date_display')->nullable();
            $table->dateTime('cate_date_hidden')->nullable();
            $table->string('language');
            $table->boolean('defaults')->default(false);
            $table->timestamps();
            $table->unique(['language','cate_url']);
        });
        DB::statement('ALTER TABLE `categories` DROP PRIMARY KEY, ADD PRIMARY KEY (`id`, `language`) USING BTREE');


        #flook mockup
        DB::table('categories')->insert([
            [
                'id' => 1,
                'cate_url' => 'หน้าหลัก',
                'cate_title' => 'หน้าหลัก',
                'cate_keyword' => 'home',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_product_cate' => false,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 1,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 2,
                'cate_url' => 'อินเตอร์เน็ตไฟเบอร์',
                'cate_title' => 'อินเตอร์เน็ตไฟเบอร์',
                'cate_keyword' => 'internet_fiber',
                'cate_description' => 'เน็ตแรงที่สุด 2Gbps ดูเต็มอิ่ม หนัง กีฬา ความบันเทิง | True Gigatex PRO',
                'cate_redirect' => 'fiber',
                'is_menu' => true,
                'is_product_cate' => false,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 2,
                'cate_thumbnail' => 'upload/2023/11/30/wifi.png',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 3,
                'cate_url' => 'เบอร์มงคล',
                'cate_title' => 'เบอร์มงคล',
                'cate_keyword' => 'lucky_number',
                'cate_description' => 'เบอร์มงคล พร้อมแพ็กเกจ ที่คุณอาจสนใจ',
                'cate_redirect' => 'bermonthly',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 3,
                'cate_thumbnail' => 'upload/2023/11/30/simcard.png',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 4,
                'cate_url' => 'เติมเงิน',
                'cate_title' => 'เติมเงิน',
                'cate_keyword' => 'prepaid',
                'cate_description' => 'ซิมเติมเงิน พร้อมแพ็กเกจเสริม ที่คุณอาจสนใจ',
                'cate_redirect' => 'prepaid_sim',
                'is_menu' => true,
                'is_product_cate' => false,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 4,
                'cate_thumbnail' => 'upload/2023/11/30/box.png',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 5,
                'cate_url' => 'ย้ายค่าย',
                'cate_title' => 'ย้ายค่าย',
                'cate_keyword' => 'move',
                'cate_description' => '',
                'cate_redirect' => 'move',
                'is_menu' => true,
                'is_product_cate' => false,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 5,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 6,
                'cate_url' => 'ซิมท่องเที่ยว',
                'cate_title' => 'ซิมท่องเที่ยว',
                'cate_keyword' => 'travel',
                'cate_description' => 'ซิมสำหรับท่องเที่ยว เชื่อมต่อได้ไม่มีสะดุด',
                'cate_redirect' => 'travel_sim',
                'is_menu' => true,
                'is_product_cate' => false,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 6,
                'cate_thumbnail' => 'upload/2023/11/30/pilot.png',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 7,
                'cate_url' => 'วิธีการสั่งซื้อ',
                'cate_title' => 'วิธีการสั่งซื้อ',
                'cate_keyword' => 'how_to_order',
                'cate_description' => '',
                'cate_redirect' => '/howtobuy/fiber',
                'is_menu' => true,
                'is_product_cate' => false,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => false,
                'cate_priority' => 7,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 8,
                'cate_url' => 'สิทธิประโยชน์',
                'cate_title' => 'สิทธิประโยชน์',
                'cate_keyword' => 'benefit_items',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => false,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true, // สำหรับ product
                'cate_priority' => 8,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 9,
                'cate_url' => 'สิทธิพิเศษ',
                'cate_title' => 'สิทธิพิเศษ',
                'cate_keyword' => 'privileges',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => false,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true, // สำหรับ product
                'cate_priority' => 9,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 10,
                'cate_url' => 'เน็ตบ้านทรู&ดีแทค',
                'cate_title' => 'เน็ตบ้าน สำหรับทรูและดีแทค',
                'cate_keyword' => 'True Gigatex PRO Special.',
                'cate_description' => 'แพ็กราคาสุดพิเศษ สำหรับลูกค้าดีแทค และ ทรูมูฟเอช รายเดือนเท่านั้น สนใจสมัครด้วยตนเองที่นี่ หรือ โทร 02-700-8000',
                'cate_redirect' => 'fiber/true_dtac/เน็ตบ้านทรู&ดีแทค',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2, // อินเตอร์เน็ตไฟเบอร์
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 10,
                'cate_thumbnail' => 'upload/2023/11/22/trueanddtac.png',
                'cate_thumbnail_title' => 'true and dtac',
                'cate_thumbnail_alt' => 'true and dtac',
            ],
            [
                'id' => 11,
                'cate_url' => 'เน็ตบ้านพื้นฐาน',
                'cate_title' => 'เน็ตบ้าน สำหรับใช้งานพื้นฐาน',
                'cate_keyword' => 'True Gigatex PRO',
                'cate_description' => 'ครบกว่า คุ้มกว่า แรงกว่าทุกกระแส ดูเต็มอิ่ม หนัง กีฬา ความบันเทิง',
                'cate_redirect' => 'fiber/true_dtac/เน็ตบ้านพื้นฐาน',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2, // อินเตอร์เน็ตไฟเบอร์
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 11,
                'cate_thumbnail' => 'upload/2023/11/22/standard.png',
                'cate_thumbnail_title' => 'standard',
                'cate_thumbnail_alt' => 'standard',
            ],
            [
                'id' => 12,
                'cate_url' => 'เน็ตบ้านพร้อมประกัน',
                'cate_title' => 'เน็ตบ้าน พร้อมประกัน',
                'cate_keyword' => 'True Gigatex PRO Security',
                'cate_description' => 'แพ็กเกจเน็ตบ้าน ครอบคลุมทุกย่าน ด้วยความห่วงใย',
                'cate_redirect' => 'fiber/true_dtac/เน็ตบ้านพร้อมประกัน',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2, // อินเตอร์เน็ตไฟเบอร์
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 12,
                'cate_thumbnail' => 'upload/2023/11/22/waranty.png',
                'cate_thumbnail_title' => 'waranty',
                'cate_thumbnail_alt' => 'waranty',
            ],
            [
                'id' => 13,
                'cate_url' => 'เน็ตบ้านพร้อมทรูวิชั่นส์',
                'cate_title' => 'เน็ตบ้าน พร้อมทรูวิชั่นส์',
                'cate_keyword' => 'True Gigatex PRO CYOD',
                'cate_description' => 'ทางเลือกสุดคุ้ม นำเราเตอร์ของคุณเองมาใช้ ร่วมกับแพ็กเกจเน็ตบ้านทรู ราคาสุดพิเศษ',
                'cate_redirect' => 'fiber/true_dtac/เน็ตบ้านพร้อมทรูวิชั่นส์',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2, // อินเตอร์เน็ตไฟเบอร์
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 13,
                'cate_thumbnail' => 'upload/2023/11/22/truevision.png',
                'cate_thumbnail_title' => 'truevision',
                'cate_thumbnail_alt' => 'truevision',
            ],
            [
                'id' => 14,
                'cate_url' => 'เน็ตบ้านพร้อมเราเตอร์',
                'cate_title' => 'เน็ตบ้าน เลือกเราเตอร์เอง',
                'cate_keyword' => 'True Gigatex PRO Gold',
                'cate_description' => 'กล่องทรูไฮบริด พร้อมคอนเทนท์พรีเมียม | สตรีมมิง | แอพสุดฮิต มาพร้อมเน็ตบ้านไฟเบอร์ทรู 1Gbps',
                'cate_redirect' => 'fiber/true_dtac/เน็ตบ้านพร้อมเราเตอร์',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2, // อินเตอร์เน็ตไฟเบอร์
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 14,
                'cate_thumbnail' => 'upload/2023/11/22/selectroute.png',
                'cate_thumbnail_title' => 'select router',
                'cate_thumbnail_alt' => 'select router',
            ],
            [
                'id' => 15,
                'cate_url' => 'เน็ตบ้านสำหรับเกมเมอร์',
                'cate_title' => 'เน็ตบ้าน สำหรับเกมเมอร์',
                'cate_keyword' => 'True Gigatex PRO Gamer',
                'cate_description' => 'แพ็กเกจเน็ตบ้าน ครอบคลุมทุกย่าน ด้วยความห่วงใย',
                'cate_redirect' => 'fiber/true_dtac/เน็ตบ้านสำหรับเกมเมอร์',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2, // อินเตอร์เน็ตไฟเบอร์
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 15,
                'cate_thumbnail' => 'upload/2023/11/22/gaming.png',
                'cate_thumbnail_title' => 'gaming',
                'cate_thumbnail_alt' => 'gaming',
            ],
            [
                'id' => 16,
                'cate_url' => 'เน็ตบ้านสำหรับsme',
                'cate_title' => 'เน็ตบ้าน สำหรับธุรกิจ SME',
                'cate_keyword' => 'True Gigatex PRO SME',
                'cate_description' => 'เน็ตเร็ว แรง เพื่อธุรกิจ ฟรีค่าโทร พร้อมบริการ Public Fixed IP กับ True Gigatex PRO SME',
                'cate_redirect' => 'fiber/true_dtac/เน็ตบ้านสำหรับsme',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2, // อินเตอร์เน็ตไฟเบอร์
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 16,
                'cate_thumbnail' => 'upload/2023/11/22/sme.png',
                'cate_thumbnail_title' => 'sme',
                'cate_thumbnail_alt' => 'sme',
            ],
            [
                'id' => 17,
                'cate_url' => 'ซิมเติมเงิน',
                'cate_title' => 'ซิมเติมเงิน',
                'cate_keyword' => 'prepaid_sim',
                'cate_description' => '',
                'cate_redirect' => 'prepaid_sim/sim_includ',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 4, // เติมเงิน
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 17,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 18,
                'cate_url' => 'แพ็กเกจเสริม',
                'cate_title' => 'แพ็กเกจเสริม',
                'cate_keyword' => 'additional_packages',
                'cate_description' => '',
                'cate_redirect' => 'prepaid_sim/package',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 4, // เติมเงิน
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 18,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 19,
                'cate_url' => 'ย้ายค่าย/FixxyNoLimit',
                'cate_title' => 'Fixxy No Limit',
                'cate_keyword' => 'fixxy_no_limit',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_product_cate' => true,
                'is_topside' => false,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 5, // ย้ายค่าย
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 19,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 20,
                'cate_url' => 'ย้ายค่าย/5GTogether+',
                'cate_title' => '5G Together+',
                'cate_keyword' => '5g_together+',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_product_cate' => true,
                'is_topside' => false,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 5, // ย้ายค่าย
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 20,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 21,
                'cate_url' => 'ย้ายค่าย/5GSuperSmart',
                'cate_title' => '5G Super Smart',
                'cate_keyword' => '5g_super_smart',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_product_cate' => true,
                'is_topside' => false,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 5, // ย้ายค่าย
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 21,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 22,
                'cate_url' => 'เดินทางไปต่างประเทศ',
                'cate_title' => 'เดินทางไปต่างประเทศ',
                'cate_keyword' => 'Thailand Tourist sim',
                'cate_description' => 'ซิมสำหรับท่องเที่ยวต่างประเทศ เชื่อมต่อได้ไม่มีสะดุด',
                'cate_redirect' => 'travel_sim/travelling',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 6, // ซิมท่องเที่ยว
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 23,
                'cate_thumbnail' => 'upload/2023/12/08/icon-park_elephant.png',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 23,
                'cate_url' => 'มาเที่ยวในไทย',
                'cate_title' => 'มาเที่ยวในไทย',
                'cate_keyword' => 'Thailand Tourist infinite sim',
                'cate_description' => 'ซิมสำหรับท่องเที่ยวในประเทศไทย เชื่อมต่อได้ไม่มีสะดุด',
                'cate_redirect' => 'travel_sim/visiting',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 6, // ซิมท่องเที่ยว
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 22,
                'cate_thumbnail' => 'upload/2023/12/08/pilot.png',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 24,
                'cate_url' => 'howtobuy/fiber',
                'cate_title' => 'อินเตอร์เน็ตไฟเบอร์',
                'cate_keyword' => 'อินเตอร์เน็ตไฟเบอร์',
                'cate_description' => 'การสั่งซื้ออินเตอร์เน็ตไฟเบอร์',
                'cate_redirect' => 'howtobuy/fiber',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 7, // ซิมท่องเที่ยว
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 24,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 25,
                'cate_url' => 'howtobuy/month',
                'cate_title' => 'เบอร์มงคลรายเดือน',
                'cate_keyword' => 'เบอร์มงคลรายเดือน',
                'cate_description' => 'การสั่งซื้อเบอร์มงคลรายเดือน',
                'cate_redirect' => 'howtobuy/month',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 7, // ซิมท่องเที่ยว
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 25,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 26,
                'cate_url' => 'howtobuy/paysim',
                'cate_title' => 'ซิมเติมเงิน',
                'cate_keyword' => 'ซิมเติมเงิน',
                'cate_description' => 'การสั่งซื้อซิมเติมเงิน',
                'cate_redirect' => 'howtobuy/paysim',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 7, // ซิมท่องเที่ยว
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 26,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ],
            [
                'id' => 27,
                'cate_url' => 'howtobuy/travelsim',
                'cate_title' => 'ซิมท่องเที่ยว',
                'cate_keyword' => 'ซิมท่องเที่ยว',
                'cate_description' => 'การสั่งซื้อซิมท่องเที่ยว',
                'cate_redirect' => 'howtobuy/travelsim',
                'is_menu' => true,
                'is_product_cate' => true,
                'is_topside' => true,
                'is_bottomside' => true,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 7, // ซิมท่องเที่ยว
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'on_product' => true,
                'cate_priority' => 27,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
            ]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('categories');
    }
};
